# Generated by Django 3.1.6 on 2021-02-16 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('cinemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True, primary_key=True,
                     serialize=False, verbose_name='ID'
                 )
                 ),
                ('datetime', models.DateTimeField()),
                ('cinema', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='cinemas.cinema')),
                ('movie', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='movies.movie')),
            ],
        ),
    ]
