# Generated by Django 3.1.6 on 2021-02-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID'
                )
                ),
                ('title', models.CharField(max_length=200, unique=True)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('preview', models.CharField(blank=True, max_length=200)),
                ('trailer', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
